name: python backend App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 Backend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      
    - name: setup python and poetry 
      uses: actions/setup-python@v1
    - run: |
        pip install -U pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
  
    - name: Build App
      run: |
       bash ./prestart.sh
       uvicorn app.main:app --reload
      working-directory: ./backend
    

    
